jwtSecret: aabbccdd
logging:
  config: classpath:logback-spring-${spring.profiles.active}.xml
server:
  port: 8088
  servlet:
    context-path: /pocketbook/api
spring:
  profiles:
    active: dev
  application:
    name: pocketbook
  cache:
    type: redis
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  # classpath后面加*，值里面的*才起作用
  mapper-locations: classpath*:mapper/*.xml