spring:
  datasource:  #数据源
    url: jdbc:mysql://127.0.0.1:3306/pocketbook?characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    driverClassName: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      # 连接池中维护的最小空闲连接数
      minimum-idle: 5
      # 配置最大池大小
      maximum-pool-size: 15
      # 配置从池返回的连接的默认自动提交行为。默认值为true。
      auto-commit: true
      # 允许连接在连接池中空闲的最长时间（以毫秒为单位）
      idle-timeout: 30000
      # 连接池的用户定义名称，主要出现在日志记录和JMX管理控制台中以识别池和池配置
      pool-name: HikariDataPool
      # 池中连接关闭后的最长生命周期（以毫秒为单位）
      max-lifetime: 1800000
      # 客户端等待连接池连接的最大毫秒数
      connection-timeout: 30000
      # 测试连接
      connection-test-query: select 1 from dual